export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const LOADING_DIVISION = "LOADING_DIVISION";
export const LOADED_DIVISION = "LOADED_DIVISION";
export const LOADED_DIVISIONS = "LOADED_DIVISIONS";
export const ERROR_DIVISION = "ERROR_DIVISION";
export const SUCCESS_DIVISION = "SUCCESS_DIVISION";
export const DELETE_DIVISION = "DELETE_DIVISION";