export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const LOADING_DIVISION = "LOADING_DIVISION";
export const LOADED_DIVISION = "LOADED_DIVISION";
export const LOADED_DIVISIONS = "LOADED_DIVISIONS";
export const ERROR_DIVISION = "ERROR_DIVISION";
export const SUCCESS_DIVISION = "SUCCESS_DIVISION";
export const DELETE_DIVISION = "DELETE_DIVISION";

export const LOADING_POSITION = "LOADING_POSITION";
export const LOADED_POSITION = "LOADED_POSITION";
export const LOADED_POSITIONS = "LOADED_POSITIONS";
export const ERROR_POSITION = "ERROR_POSITION";
export const SUCCESS_POSITION = "SUCCESS_POSITION";
export const DELETE_POSITION = "DELETE_POSITION";

export const LOADING_EMPLOYEE = "LOADING_EMPLOYEE";
export const LOADED_EMPLOYEE = "LOADED_EMPLOYEE";
export const LOADED_EMPLOYEES = "LOADED_EMPLOYEES";
export const ERROR_EMPLOYEE = "ERROR_EMPLOYEE";
export const SUCCESS_EMPLOYEE = "SUCCESS_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";

export const LOADING_CATEGORY = "LOADING_CATEGORY";
export const LOADED_CATEGORY = "LOADED_CATEGORY";
export const LOADED_CATEGORYS = "LOADED_CATEGORYS";
export const ERROR_CATEGORY = "ERROR_CATEGORY";
export const SUCCESS_CATEGORY = "SUCCESS_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const LOADING_DOORLOCK = "LOADING_DOORLOCK";
export const LOADED_DOORLOCK = "LOADED_DOORLOCK";
export const LOADED_DOORLOCKS = "LOADED_DOORLOCKS";
export const ERROR_DOORLOCK = "ERROR_DOORLOCK";
export const SUCCESS_DOORLOCK = "SUCCESS_DOORLOCK";
export const DELETE_DOORLOCK = "DELETE_DOORLOCK";