export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const LOADING_DIVISION = "LOADING_DIVISION";
export const LOADED_DIVISION = "LOADED_DIVISION";
export const LOADED_DIVISIONS = "LOADED_DIVISIONS";
export const ERROR_DIVISION = "ERROR_DIVISION";
export const SUCCESS_DIVISION = "SUCCESS_DIVISION";
export const DELETE_DIVISION = "DELETE_DIVISION";

export const LOADING_POSITION = "LOADING_POSITION";
export const LOADED_POSITION = "LOADED_POSITION";
export const LOADED_POSITIONS = "LOADED_POSITIONS";
export const ERROR_POSITION = "ERROR_POSITION";
export const SUCCESS_POSITION = "SUCCESS_POSITION";
export const DELETE_POSITION = "DELETE_POSITION";